var num1 = 20;
var num2 = 10;
var result = 0;
result = num1 + num2;
console.log("sum:" + result);
result = num1 - num2;
console.log("difference:" + result);
result = num1 * num2;
console.log("multiplication:" + result);
result = num1 / num2;
console.log("division:" + result);
result = num1 % num2;
console.log("modulation:" + result);
result = num1 || num2;
console.log("OR:" + result);
result = num1 ^ num2;
console.log("Exc:" + result);
result = num1 && num2;
console.log("And:" + result);
